---
- name: "Setup pi"
  hosts: all
  vars_files:
    - vars/secrets.yaml
  vars:
    proxy_env:
      http_proxy: "{{ http_proxy }}"
      https_proxy: "{{ http_proxy }}"
    screenly_repo: "https://github.com/Screenly/screenly-ose.git"
  tasks:
    - name: "Ensure pi-user has not the default password."
      become: true
      user:
        name: "pi"
        password: "{{ pi_password }}"
        state: present

    - name: "update all"
      become: true
      apt:
        upgrade: dist
        cache_valid_time: 3600

    - name: "Ensure the right timezone is set"
      become: true
      timezone:
        name: "Europe/Berlin"

    - name: "Disable overscan"
      lineinfile:
        path: /boot/config.txt
        regexp: "^#\\s*disable_overscan.*$"
        line: "disable_overscan=1"
        state: present
      become: true

    - name: "Enable HDMI hotblug"
      lineinfile:
        path: /boot/config.txt
        regexp: "^#\\s*hdmi_force_hotplug.*$"
        line: "hdmi_force_hotplug=1"
        state: present
      become: true

    - name: "Install packages"
      become: true
      apt:
        name: ["python-setuptools", "python-pip", "python-pyasn1", "git"]
        state: present
        autoclean: true

    - name: clone Screenly repo
      git:
        repo: "{{ screenly_repo }}"
        dest: /home/pi/screenly
        version: "production"
        update: true

- name: Install Screenly
  import_playbook: screenly-ose-ansible/site.yml

- name: "Configure Screenly"
  hosts: all
  tasks:
#    - name: "set user"
#      lineinfile:
#        dest: /home/pi/.screenly/screenly.conf
#        regexp: "{{ item.regexp }}"
#        line: "{{ item.line }}"
#      with_items:
#        - regexp: "^user(\\s*)=.*$"
#          line: "user=test"
#        - regexp: "^password(\\s*)=.*$"
#          line: "password=ff2bea10041cceb054dd6417bc70e8e796edb94dfaeb7046b536509743fab619" #echo -n "password" | openssl dgst -sha256

#    - name: "set default assets"
#      copy:
#        src: default_assets.yml
#        dest: /home/pi/.screenly/default_assets.yml

#    - name: "use default assets"
#      lineinfile:
#        dest: /home/pi/.screenly/screenly.conf
#        regexp: "^default_assets(\\s*)=.*$"
#        line: "default_assets = on"

    - name: "reboot"
      become: true
      reboot: