---
- name: "Setup pi"
  hosts: all
  vars_files:
    - vars/secrets.yaml
  vars:
    screenly_repo: "https://github.com/Screenly/screenly-ose.git"

  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ http_proxy }}"

  tasks:
    - name: "Ensure pi-user has not the default password."
      become: true
      user:
        name: "pi"
        password: "{{ pi_password }}"
        state: present

    - name: "update all"
      become: true
      apt:
        upgrade: dist
        cache_valid_time: 3600

    - name: "Ensure the right timezone is set"
      become: true
      timezone:
        name: "Europe/Berlin"

    - name: "HDMI settings"
      lineinfile:
        path: /boot/config.txt
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      with_items:
        - { regexp: '^#\s*hdmi_force_hotplug.*$', line: 'hdmi_force_hotplug=1' }
        - { regexp: '^#\s*disable_overscan.*$', line: 'disable_overscan=1' }
        - { regexp: '^#\s*hdmi_group.*$', line: 'hdmi_group=1' }
        - { regexp: '^#\s*hdmi_mode.*$', line: 'hdmi_mode={{ resolution }}' }
      become: true

    - name: "Install packages"
      become: true
      apt:
        name: ["python-setuptools", "python-pip", "python-pyasn1", "git"]
        state: present
        autoclean: true

    - name: clone Screenly repo
      git:
        repo: "{{ screenly_repo }}"
        dest: /home/pi/screenly
        version: "production"
        update: true

- name: Install Screenly
  import_playbook: screenly-ose-ansible/site.yml

- name: Install Redsocks
  import_playbook: redsocks.yaml

- name: "Reboot"
  hosts: all
  tasks:
    - name: "reboot"
      become: true
      reboot: